### PR TITLE
Implementation of the GetUpdated Endpoint

### PR DESCRIPTION
**Pull request by web-connect**
Implements https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_getupdated.htm

### CODE REVIEW

**Comment by timrogers** [comment]
The specs are currently failing for me - but only two of them. Can you fix and ping me once you have? Thanks for the PR! :+1:

**Comment by web-connect** [comment]
Ahh the ole build server is in a different timezone edgecase. Fixed the test. Also formatted the code to comply with Rubocop

**Comment by timrogers** [comment]
@web-connect Cheers! If you have a clue as to why Travis has started failing the builds, please do tell :sob: Happened a couple of weeks back with no changes to the code.

**Comment by timrogers** [comment]
(Will try it locally and get this merged a bit later on.)

**Comment by web-connect** [comment]
Great thanks! I don't know off hand. I did see them pop up. I'll take a look. I created issue #201 to track it. The good thing is that the build fails in the same way locally.

**Comment by timrogers** [comment]
:+1:

**Comment by timrogers** [comment]
I've just released this as part of v2.1.1 (<https://github.com/ejholmes/restforce/releases/tag/v2.1.1>) - it's on Rubygems too.

**Pull request merged**
