### PR TITLE
allow pages to be garbage collected while iterating over collection

### PR DESCRIPTION
**Pull request by th7**
Related to #106 (memory usage with large datasets)

### CODE REVIEW

**Comment by theSteveMitchell** [comment]
I've been using this branch in production for 5 months and everything is working well...

**Comment by theSteveMitchell** [comment]
@ejholmes @bramswenson @zenchild Do you guys have any thoughts on this?  I think it's worthy of a bump, as my production environment grinds to a halt using master, but runs well on this branch.

**Comment by zenchild** [comment]
Thumbs up here. I didn't have a large dataset in my test org to try it out on but the results are evident fairly soon. Here are two benchmarks that output the process size for each page iteration. The first is the code prior to this patch, the second is with the patch.

```
# Without patch
Page1: Process size (bytes): 42721280
Page2: Process size (bytes): 45887488
Page3: Process size (bytes): 52195328
Page4: Process size (bytes): 55898112
Page5: Process size (bytes): 59555840
```

```
# With patch
Page1: Process size (bytes): 45748224
Page2: Process size (bytes): 48709632
Page3: Process size (bytes): 48967680
Page4: Process size (bytes): 49000448
Page5: Process size (bytes): 42881024
```

**Comment by theSteveMitchell** [comment]
thanks @zenchild. can we get this merged?

**Comment by zenchild** [comment]
I'd love to @theSteveMitchell but I don't have commit for this repo. cc: @ejholmes

**Comment by ejholmes** [comment]
Sorry for the delay! This looks good to me. I'll cut a new release.

**Comment by ejholmes** [comment]
Released 1.5.2

**Pull request merged**
