### PR TITLE
Update raise_error

### PR DESCRIPTION
**Pull request by debussyman**

### CODE REVIEW

**Comment by ryansch** [comment]
:+1:

**Comment by timrogers** [comment]
What's the use case for this? Would like to understand better before merging.

**Comment by timrogers** [comment]
Taggingin @ryansch and @debussyman to weigh in on this.

**Comment by debussyman** [comment]
@timrogers this resolves the issue outlined in https://github.com/ejholmes/restforce/issues/165

The signature of Faraday ClientError changed in version 0.9+, which meant that errors raised by Restforce not longer had any of the underlying details. Code utilizing Restforce could not distinguish between different kinds of Faraday::Error::ClientError nor see the response body

**Comment by timrogers** [comment]
@debussyman Ah, got it - didn't spot your reference to #165 in the commit message. I'll merge this later today.

**Pull request merged**
