### PR TITLE
add support for query_all in api version 29+

### PR DESCRIPTION
**Pull request by theSteveMitchell**
I stumbled across a new surprise feature of the Salesforce rest api.  The query endpoint doesn't return
1. Deleted records (even those still in the soft-deleted or recycle bin state.  
2. Archived records (tasks and events are archived automatically by Salesforce, based on some very complex rules)

according to http://www.salesforce.com/us/developer/docs/api_rest/index_Left.htm#CSHID=resources_queryall.htm|StartTopic=Content%2Fresources_queryall.htm|SkinName=webhelp

the QueryALL rest endpoint is available in api version 29.0 or later.  This will give us both soft-deleted and archived records. I opted to add a query_all method on concerns/api, so the existing behavior for query would not change.

### CODE REVIEW

**Comment by timrogers** [comment]
@theSteveMitchell Generally happy to merge this after #178 - would like to use the `version_guard` approach from there which nicely standardises things.

**Comment by theSteveMitchell** [comment]
Sure thing.  I will go ahead and rebase this on #178

**Comment by timrogers** [comment]
@theSteveMitchell (FYI, if you haven't seen, we're Ruby 1.9.3 and later now as of 2.0.0)

**Comment by timrogers** [comment]
Implemented by #193.

**Comment by theSteveMitchell** [comment]
@timrogers Cool bro.  Thanks for copying

**Comment by timrogers** [comment]
No worries! I'll credit you in the 2.1.0 changelog, going out this evening.

**Pull request closed without merging**
