### PR TITLE
Add query explain method to api

### PR DESCRIPTION
**Pull request by zenchild**
This builds on pull request #177 so you'll see some duplication between that request and this one. The reason is because I needed the `version_guard` method.

https://www.salesforce.com/us/developer/docs/api_rest/Content/dome_query_explain.htm

### CODE REVIEW

**Comment by timrogers** [comment]
@zenchild Can you draft a readme entry for this before I merge please? I'd do it myself, but I don't understand this part of the Salesforce API intimately enough.

**Comment by timrogers** [comment]
@zenchild (PS: Happy with your approach to version-handling, looks sane to me.)

**Comment by zenchild** [comment]
I'll try and get a README entry in soon.

**Comment by timrogers** [comment]
Thanks! :+1: Big fan of the `version_guard` approach.

**Comment by timrogers** [comment]
Incorported by #193.

**Pull request closed without merging**
